### ISSUE TITLE
More than one class name generates issues with fitText

### ISSUE THREAD

**Issue by Syridiana** [mediamonks/display-temple#13]
Whenever I use more than one class name in my text tag in my .hbs file:

```
<div class="title_container">
  <div class="title another_class">Some text</div>
</div>
```

And I try to use the util on that element:

```
const title = document.body.querySelector('.title');
const ctaCopy = document.body.querySelector('.cta_copy');

fitText([title, ctaCopy]);
```

The util stops working for that element.

**Comment by alandawi** [comment]
@Syridiana do you have an error log? To debug the issue. Thanks

**Comment by Syridiana** [comment]
I can't reproduce it, I think I've mistaken this for another problem. I will close for now.

**Comment by Syridiana** [comment]
I can't reproduce it, I think I've mistaken this for another problem. I will close for now.
